function Database()
{
	const Index = [
		["Studybyte", "https://light-lens.github.io/Studybyte"],
		["Light-Lens (Light-Lens) · GitHub", "https://github.com/Light-Lens"],
		["Light-Lens/Glass - Github", "https://github.com/Light-Lens/Glass"],
		["Light-Lens/Studybyte - Github", "https://github.com/Light-Lens/Studybyte"],
		["Light-Lens/Hexa - Github", "https://github.com/Light-Lens/Hexa"],
		["Light-Lens/AOs - Github", "https://github.com/Light-Lens/AOs"],
		["GitHub: Where the world builds software · GitHub", "https://github.com"],
		["Sign in to GitHub · GitHub", "https://github.com/login"],
		["Join GitHub · GitHub", "https://github.com/join"],
		["GitHub - Wikipedia", "https://en.wikipedia.org/wiki/GitHub"],
		["GitHub · GitHub", "https://github.com/Github"],
		["Git", "https://git-scm.com"],
		["Google", "http://www.google.com"],
		["Google", "http://www.google.co.in"],
		["Search - Google", "http://www.google.co.in/search"],
		["Browse All of Google's Products & Services - Google", "https://about.google/products"],
		["Google - Workplace & Office | Facebook - 2,224 Photos", "https://www.facebook.com/Google"],
		["Sign in - Google Accounts", "https://accounts.google.com/login"],
		["Google for Education", "https://edu.google.co.in"],
		["Privacy Policy – Privacy & Terms – Google", "https://policies.google.com/privacy?hl=en-US"],
		["YouTube", "http://www.youtube.com"],
		["Trending - YouTube", "https://www.youtube.com/feed/trending"],
		["YouTube Premium", "https://www.youtube.com/premium"],
		["YouTube Studio", "https://studio.youtube.com"],
		["YouTube Music", "https://music.youtube.com"],
		["YouTube - Home | Facebook", "https://www.facebook.com/youtube"],
		["YouTube (@YouTube) · Twitter", "https://twitter.com/YouTube?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"],
		["YouTube Official Blog", "https://blog.youtube"],
		["Wikipedia", "https://www.wikipedia.org"],
		["Wikipedia, the free encyclopedia", "https://en.wikipedia.org/wiki/Main_Page"],
		["Wikipedia - Wikipedia", "https://en.wikipedia.org/wiki/Wikipedia"],
		["Wikipedia | Article about Wikipedia by The Free Dictionary", "https://encyclopedia2.thefreedictionary.com/Wikipedia"],
		["Wikipedia (@Wikipedia) · Twitter", "https://twitter.com/Wikipedia?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"],
		["Encyclopedia Britannica | Britannica", "https://www.britannica.com"],
		["Trivia Quizzes | Britannica", "https://www.britannica.com/quiz/browse"],
		["Britannica Online", "https://www.britannica.com/topic/Britannica-Online"],
		["Biographies browse | Britannica", "https://www.britannica.com/biographies"],
		["India | History, Map, Population, Economy, & Facts | Britannica", "https://www.britannica.com/place/India"],
		["Encyclopædia Britannica - Wikipedia", "https://en.wikipedia.org/wiki/Encyclop%C3%A6dia_Britannica"],
		["Encyclopaedia Britannica (@Britannica) · Twitter", "https://twitter.com/Britannica?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"],
		["Learn CBSE", "https://www.learncbse.in"],
		["NCERT Solutions for Class 9 - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-9"],
		["NCERT Solutions - Learn CBSE", "https://www.learncbse.in/ncert-solutions-2"],
		["NCERT Solutions for Class 8 - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-8"],
		["Textbook Solutions - Learn CBSE", "https://www.learncbse.in/textbook-solutions"],
		["NCERT Solutions for Class 7 - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-7"],
		["NCERT Solutions for Class 6 - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-6"],
		["Revision Notes - Learn CBSE", "https://www.learncbse.in/cbse-notes"],
		["CBSE Sample Papers - Learn CBSE", "https://www.learncbse.in/cbse-sample-papers"],
		["NCERT Books for all Classes 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1 - Learn CBSE", "https://www.learncbse.in/ncert-books"],
		["NCERT Solutions for Class 5 - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-5"],
		["Learn CBSE Forum - Learn CBSE", "https://ask.learncbse.in"],
		["Tiwari Academy - A Step towards free Education", "https://www.tiwariacademy.com"],
		["Free CBSE NCERT Solution 2020-2021 - Tiwari Academy", "https://www.tiwariacademy.com/ncert-solutions"],
		["NCERT Books PDF For Class 1st To 12th English And Hindi Medium - Tiwari Academy", "https://www.tiwariacademy.com/ncert-books"],
		["CBSE Sample Papers For 9, 10, 11 & 12 - Tiwari Academy", "https://www.tiwariacademy.com/cbse-sample-papers"],
		["CBSE Sample Papers for Class 10 Session 2020-2021 - Tiwari Academy", "https://www.tiwariacademy.com/cbse-sample-papers/class-10"],
		["Tiwari Academy - YouTube", "https://www.youtube.com/channel/UClc7F_LEMPH2VRCxJwvvrlg"],
		["Tiwari Academy - Home | Facebook", "https://www.facebook.com/tiwariacademy"],
		["Brainly - For students. By students.", "https://brainly.in"],
		["Textbook Solutions - Brainly", "https://brainly.in/textbook-solutions"],
		["Ask Your Question - Brainly", "https://brainly.com/question/add?entry=1610"],
		["Brainly - Wikipedia", "https://en.wikipedia.org/wiki/Brainly"],
		["Brainly | LinkedIn", "https://www.linkedin.com/company/brainly-com"],
		["NCERT", "https://ncert.nic.in"],
		["NCERT E-Books", "https://ncert.nic.in/textbook.php"],
		["Textbooks PDF (I-XII)", "https://ncert.nic.in/textbook.php?fess1=0-11"],
		["eResources", "https://ncert.nic.in/eresources.php"],
		["NCERT Solutions for Class 5 - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-5"],
		["NCERT Solutions for Class 5 Maths Math Magic (Updated for 2019 - 20) - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-5-mathematics"],
		["Class 5 maths (India) | NCERT | Khan Academy", "https://www.khanacademy.org/math/in-in-class-5th-math-cbse"],
		["NCERT Solutions for Class 5 Maths - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-5-mathematics"],
		["Class 5 - Syllabus, Question Papers and Solutions", "https://www.toppr.com/class/5"],
		["NCERT Solutions for Class 5 EVS Free PDF Download (All Chapters)", "https://www.toppr.com/guides/ncert-solutions-class-5-evs-free-pdf-download"],
		["NCERT Solutions for Class 5 EVS - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-5-evs"],
		["Free NCERT Solutions for Class 5 | Extramarks", "https://www.extramarks.com/ncert-solutions-for-class-5"],
		["NCERT Solutions for Class 5 English - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-5-english"],
		["CBSE NCERT Books For Class 5 EVS - Embibe", "https://www.embibe.com/exams/ncert-books-for-class-5-evs"],
		["NCERT Books For Class 5 All Subjects - Download Free PDFs", "https://byjus.com/ncert-books-for-class-5"],
		["Class 5 – CBSE Online", "https://cbse.online/class-5"],
		["Online Study Material for Class 5 - Topperlearning", "https://www.topperlearning.com/study/junior/class-5/b122c105"],
		["NCERT Solutions for Class 5 Hindi - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-5-hindi"],
		["Syllabus, Questions for CBSE Class 5 Maths - Cuemath", "https://www.cuemath.com/class-5-maths"],
		["Vidyartha", "https://vidyartha.com"],
		["Vidyartha - Login", "https://app.vidyartha.com"],
		["Vidyartha - Create account", "https://vidyartha.com/signup"],
		["Vidyartha | LinkedIn", "https://in.linkedin.com/company/vidyartha"],
		["Class 6 – CBSE Online", "https://cbse.online/class-6"],
		["Class 6 - Syllabus, Question Papers and Solutions", "https://www.toppr.com/class/6"],
		["NCERT Solutions For Class 6 - CBSE - Byjus", "https://byjus.com/ncert-solutions-class-6"],
		["NCERT Solutions for Class 6 Maths - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-6-maths"],
		["NCERT Solutions for Class 6 (Updated for 2020-21) - Vedantu", "https://www.vedantu.com/ncert-solutions/ncert-solutions-class-6"],
		["NCERT Solutions Class 6 Maths - CBSE - Byjus", "https://byjus.com/ncert-solutions-class-6-maths"],
		["NCERT Solutions for Class 6 Science - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-6-science"],
		["Free NCERT Solutions for Class 6 | Extramarks", "https://www.extramarks.com/ncert-solutions-for-class-6"],
		["NCERT Solutions for Class 6 English - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-6-english"],
		["NCERT Solutions for Class 6 (Free) - Meritnation", "https://www.meritnation.com/cbse-class-6/ncert-solutions"],
		["NCERT Solutions for Class 6 Hindi - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-6-hindi"],
		["Class 7 - Syllabus, Question Papers and Solutions", "https://www.toppr.com/class/7"],
		["NCERT Solutions for Class 7 Maths (Updated for 2020 - 2021)", "https://www.learncbse.in/ncert-solutions-for-class-7-maths"],
		["NCERT Solutions for Class 7 - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-7"],
		["NCERT Solutions for Class 7 Maths Updated for 2020-21", "https://www.vedantu.com/ncert-solutions/ncert-solutions-class-7-maths"],
		["Free NCERT Solutions for Class 7 | Extramarks", "https://www.extramarks.com/ncert-solutions-for-class-7"],
		["NCERT Solutions for Class 7 Maths - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-7-maths"],
		["NCERT Solutions For Class 7 - CBSE - BYJUS", "https://byjus.com/ncert-solutions-class-7"],
		["NCERT Solutions for Class 7 Science - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-7-science"],
		["NCERT Books For Class 7 All Subjects - Download Free PDFs", "https://byjus.com/ncert-books-for-class-7"],
		["NCERT Solutions for Class 7 Maths in PDF for session 2020 - 21", "https://www.tiwariacademy.com/ncert-solutions/class-7/maths"],
		["NCERT Solutions for Class 7 English - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-7-english"],
		["Class 7 maths (India) | NCERT | Khan Academy", "https://www.khanacademy.org/math/in-in-class-7th-math-cbse"],
		["NCERT Solutions for Class 7 Hindi - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-7-hindi"],
		["Class 7 | Class Notes", "https://classnotes.org.in/class-7"],
		["Free NCERT Solutions for Class 8 | Extramarks", "https://www.extramarks.com/ncert-solutions-for-class-8"],
		["NCERT Solutions For Class 8 Maths - Tiwari Academy", "https://www.tiwariacademy.com/ncert-solutions/class-8/maths/"],
		["Class 8 - Syllabus, Date Sheets, Question Papers and Results", "https://www.toppr.com/class/8/"],
		["NCERT Solutions for Class 8 - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-8/"],
		["NCERT Solutions for Class 8 English - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-8-english/"],
		["NCERT Solutions for class 8 all subjects updated for 2020-21.", "https://www.tiwariacademy.com/ncert-solutions/class-8/"],
		["NCERT Solutions for Class 8 Maths PDF Download - Vedantu", "https://www.vedantu.com/ncert-solutions/ncert-solutions-class-8-maths"],
		["[Download Free PDF] CBSE Class 8 Maths Question Papers 2021", "https://school.edufever.com/cbse/class-8-maths-question-papers/"],
		["NCERT Solutions for Class 8 Science - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-8-science/"],
		["Class 8 maths (India) | NCERT | Khan Academy", "https://www.khanacademy.org/math/in-in-class-8th-math-cbse"],
		["NCERT Solutions For Class 8 - Download Chapterwise PDF For Free", "https://byjus.com/ncert-solutions-class-8/"],
		["NCERT Solutions for Class 8 Maths CBSE 2020-21 - Byjus", "https://byjus.com/ncert-solutions-class-8-maths/"],
		["NCERT Solutions for Class 8 Maths - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-8-maths/"],
		["Class 8 - EDUREV.IN", "https://edurev.in/cbse/class-8"],
		["Class 8 | Class Notes", "https://classnotes.org.in/class-8/"],
		["NCERT Solutions for Class 8 Hindi - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-8-hindi/"],
		["CBSE Sample Papers for Class 8 2019 -20 Session with Solutions", "https://www.learncbse.in/cbse-sample-papers-class-8/"],
		["Class 9 - CBSE / School Textbooks: Books - Amazon.in", "https://www.amazon.in/CBSE-Class-9-School-Textbooks/s?rh=n%3A4149808031%2Cp_n_feature_seventeen_browse-bin%3A4149848031"],
		["Class 9 - NCERT Solutions, Syllabus, Question Papers and Doubt Clarification", "https://www.toppr.com/class/9/"],
		["CBSE Class 9 Exam Preparation 2021- Class 9 Online Classes on Unacademy", "https://unacademy.com/goal/cbse-class-9/SUVLV"],
		["Free NCERT Solutions for Class 9 | Extramarks", "https://www.extramarks.com/ncert-solutions-for-class-9"],
		["Class 9 – CBSE Online", "https://cbse.online/class-9/"],
		["NCERT Book for Class 9 Maths PDF (Updated for 2020-2021)", "https://www.jagranjosh.com/articles/cbse-class-9-mathematics-ncert-book-1522324426-1"],
		["CBSE Class 9 - TopperLearning", "https://www.topperlearning.com/cbse-class-9"],
		["NCERT Solutions for Class 9 - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-9/"],
		["NCERT Solutions for Class 9 (Free) - Meritnation", "https://www.meritnation.com/cbse-class-9/ncert-solutions"],
		["NCERT Solutions for Class 9 Maths Updated for 2020-21 - Byjus", "https://byjus.com/ncert-solutions-class-9-maths/"],
		["Class 9 maths (India) | NCERT | Khan Academy", "https://www.khanacademy.org/math/in-in-grade-9-ncert"],
		["NCERT Solutions for Class 9 Maths - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-9-maths/"],
		["NCERT Solutions for Class 9 Maths Hindi and English Medium 2020-2021", "https://www.tiwariacademy.com/ncert-solutions/class-9/maths/"],
		["NCERT Solutions for Class 9 Science - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-9-science/"],
		["NCERT Solutions for Class 9 Maths, Science, Social Science, English & Hindi", "https://www.vedantu.com/ncert-solutions/ncert-solutions-class-9/"],
		["NCERT Solutions for Class 9 English - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-9-english/"],
		["NCERT Solutions for Class 9 Hindi - Learn CBSE", "https://www.learncbse.in/ncert-solutions-for-class-9-hindi/"]
	];

	var Link;
	var NewItem;

	let List = document.getElementById("LinkList");

	for (var i = 0; i < Index.length; i++)
	{
		Link = document.createElement("a");
		NewItem = document.createElement("li");

		Link.textContent = Index[i][0];
		Link.setAttribute('href', Index[i][1]);

		NewItem.appendChild(Link);
		List.appendChild(NewItem);
	}
}
